---
replicaCount: 2

autoscaling:
  enabled: true

ingress:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

podDisruptionBudget:
  enabled: true

hostPodAntiAffinity:
  enabled: true

networkPolicy:
  enabled: true

serviceAccount:
  enabled: true

service:
  enableAdditionalHeadlessService: true
...
