{{- if .Values.ingress.enabled -}}
---
kind: "Ingress"
apiVersion: {{ .Values.apiVersions.ingress | quote }}
metadata:
  name: {{ include "names.fullname" . | quote }}
  namespace: {{ include "names.namespace" . | quote }}
  labels:
    {{- include "labels.commonLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            {{- if .pathType }}
            pathType: {{ .pathType | quote }}
            {{- end }}
            backend:
              service:
                name: {{ include "names.fullname" $ | quote }}
                port:
                  name: {{ .servicePortName | quote }}
          {{- end }}
    {{- end }}
...
{{- end }}
