{{- if .Values.metrics.enabled -}}
---
kind: "Service"
apiVersion: {{ .Values.apiVersions.service | quote }}
metadata:
  name: {{ include "names.fullnameSuffix" (dict "suffix" "metrics" "context" .) | quote }}
  namespace: {{ include "names.namespace" . | quote }}
  labels:
    {{- include "labels.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type | quote}}
  ports:
    {{- range .Values.metrics.service.ports }}
    - name: {{ .name | quote }}
      port: {{ .port }}
      targetPort: {{ .targetPort | quote }}
      protocol: {{ .protocol | quote }}
    {{- end }}
  selector:
    {{- include "labels.matchLabels" . | nindent 4 }}
...
{{- end }}
