---
suite: "service account template"
templates:
  - "serviceaccount.yaml"
tests:
  - it: "should not render service account if disabled"
    set:
      serviceAccount:
        enabled: false
    asserts:
      - notExists:
          path: "spec"

  - it: "should render service account if enabled"
    set:
      serviceAccount:
        enabled: true
    asserts:
      - isKind:
          of: "ServiceAccount"

  - it: "should render apiVersion with default value"
    set:
      serviceAccount:
        enabled: true
    asserts:
      - equal:
          path: "apiVersion"
          value: "v1"

  - it: "should render apiVersion as set"
    set:
      apiVersions:
        serviceAccount: "v1beta1"
      serviceAccount:
        enabled: true
    asserts:
      - equal:
          path: "apiVersion"
          value: "v1beta1"

  - it: "should not render annotations if not set"
    set:
      serviceAccount:
        annotations: null
    asserts:
      - notExists:
          path: "metadata.annotations"

  - it: "should render annotations as set"
    set:
      serviceAccount:
        annotations:
          example: "value"
    asserts:
      - equal:
          path: "metadata.annotations"
          value:
            example: "value"

  - it: "should render automount token with default value"
    asserts:
      - equal:
          path: "automountServiceAccountToken"
          value: true

  - it: "should render automount token as set"
    set:
      serviceAccount:
        automount: false
    asserts:
      - equal:
          path: "automountServiceAccountToken"
          value: false
