{{- if .Values.serviceAccount.enabled -}}
---
kind: "ServiceAccount"
apiVersion: {{ .Values.apiVersions.serviceAccount | quote }}
metadata:
  name: {{ include "names.serviceAccountName" . | quote }}
  namespace: {{ include "names.namespace" . | quote }}
  labels:
    {{- include "labels.commonLabels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
...
{{- end }}
