---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yopass-valkey-credentials
  namespace: yopass
spec:
  encryptedData:
    password: AgCX3TzRtoSjJAYAkMBRI1gSRUWKqivMHuN0g76dk2nNecmVaCBDqU9JweXy2P/ap0z6OaSqrEVpDeQClcaUdAORcIVnR5AC7wTm2OquElRZqsiLDMRibB50TQTZdVe4itak47Aq5S+eE+bsEWjNfIywPelf71E6VGcI7qLFlvCOupGL0qWxzKtfL6CkP8JNeiC2/imwisnJkLAOR5E4B3H9CXdkHIZiOf50cguqr0Fbz38ZmyXt9vgjCk45n/Jd9NNFRn5+IBNWHHtA2ymD3jLty69dqRm1hKA9S8HuVdb1iSq7trBuQVDV1h6LWzS94vxOpRsNKcQIsGjtHmb0DNQMCmI7+H1NJps5gjJY941b02tRg1Nd+hNlFIa/PIsk9bFiZtI2DUglEGvvGG5PzCTWtqbwJlg+vHE5OX1LDDr/rZdQdvQyK+VnsOqMuUKBAt3nx9e+YAmj4FogqJppsj9pRrgp8K9hDC1dIUDGoB1cAWSrOupxr8X1jblm+Vsy/ksQ8300DvZ0R87BgWRdxZ0M+oAKFAyNvdnt5Q19QfB5NvW2cylIjwlMscdJQefRXv8AabZypn6XyA5YH6JFOYvENK/BVhfOU78sFf5UsOVAcKuJn1ec3eP6oI7W7tV/v1zo7Jr04lejCF1ZlJewNvWQbGL3gk8ldz/HxYsKiiIlQxZqwGiamavhqyA5ttoTn1RnAOnrqi8hIkM6S7GH/TjjpM0/EQ==
    url: AgBDI08qvhuBjJ0oKFReMphv3P/XC4rqAWG0RRbC72ypoQp4VdaZkdoG0TdlmkuIFjp/CYKuMNNaq3cyHtNUsAehfH/E42ihcaxu0OxgRv7S7Juhc+XbfW3EdL+vuenK243hPeddVoBVTPEZo2F9dXfAfe7YaeKngbZZj7RQyy4UID8EEYsISoeClvNnCPKjJshEgBVcENynpUBruzHlejAeVy4LnlT8Mq6SnFe8zTd2RD6BFmAgeC1N4XkfY/Z7tHUMEkv3QChvOs2x7JQ57Er/9QSt7mHOWHXSr1lQwMJ0xaHKKWvboBRnwd5apwlb00PD+cuy+BaKgjC9DSfcQmZrWOyoxHybDmAID9iNYcr8ENN/u2iLEp9Euzk8gU8aOcDkuRLUhYkyWXpy7ENPJ9iOoPGDimiSDBMdadgn1Fms89O644vET8SDHRNraY1CCJ+125GOYsUIlPCtet7vf4mVN7As1icqqQwgqY+QYR64a5HtuuncoFzDBhZitzuos9qQ74O3uoTRciB2XkgsGLcYRokZulR3PrjdpvcfCMtWeMenk3awYckFk9vDKrrHDTki1S6BLG3woGNmRHQhg3pkeF+bagayLxVg6rTurj77hHKZtTT2ibac1XJWnTI2Rn4b7R4YJJfigSIeOZZC+dyohgeNlTadGLWR45jyQbezK2pEiAaqaXCtn26M+z9Vn5h7OAzPB/7okIdeu1We1fugbjFmKZZwB+ljBoxoePhk4CHUXJVq0HnttxtKnAZZIJRtmlYFqw7ogA==
  template:
    metadata:
      creationTimestamp: null
      name: yopass-valkey-credentials
      namespace: yopass
    type: Opaque
